// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzlUeIiQp3Bbzf8Of5KR6N-oovvRZxDhQ',
    appId: '1:1074294349951:web:46430d8378629b4f6bdf4a',
    messagingSenderId: '1074294349951',
    projectId: 'smart-quiz-72ead',
    authDomain: 'smart-quiz-72ead.firebaseapp.com',
    storageBucket: 'smart-quiz-72ead.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCslVsTBq4NJoknmgieNWVdD2eaY5JKGNY',
    appId: '1:1074294349951:android:a90908e3131f716a6bdf4a',
    messagingSenderId: '1074294349951',
    projectId: 'smart-quiz-72ead',
    storageBucket: 'smart-quiz-72ead.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PvPvjOx15ntAVepz36jY-FC1wQapUew',
    appId: '1:1074294349951:ios:6d617c30d50a12336bdf4a',
    messagingSenderId: '1074294349951',
    projectId: 'smart-quiz-72ead',
    storageBucket: 'smart-quiz-72ead.firebasestorage.app',
    iosBundleId: 'com.example.smartQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PvPvjOx15ntAVepz36jY-FC1wQapUew',
    appId: '1:1074294349951:ios:6d617c30d50a12336bdf4a',
    messagingSenderId: '1074294349951',
    projectId: 'smart-quiz-72ead',
    storageBucket: 'smart-quiz-72ead.firebasestorage.app',
    iosBundleId: 'com.example.smartQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzlUeIiQp3Bbzf8Of5KR6N-oovvRZxDhQ',
    appId: '1:1074294349951:web:de7f7606243db4ac6bdf4a',
    messagingSenderId: '1074294349951',
    projectId: 'smart-quiz-72ead',
    authDomain: 'smart-quiz-72ead.firebaseapp.com',
    storageBucket: 'smart-quiz-72ead.firebasestorage.app',
  );
}
